"""Initial migration

Revision ID: ef72b3954921
Revises: 652e7ddc8751
Create Date: 2025-05-01 00:52:56.484747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef72b3954921'
down_revision = '652e7ddc8751'
branch_labels = None
depends_on = None


def upgrade():
    # Drop foreign key constraints
    op.drop_constraint('favourite_fav_user_id_fk_fkey', 'favourite', type_='foreignkey')
    op.drop_constraint('favourite_user_id_fk_fkey', 'favourite', type_='foreignkey')
    op.drop_constraint('profile_user_id_fk_fkey', 'profile', type_='foreignkey')

    # Drop dependent tables
    op.drop_table('favourite')
    op.drop_table('profile')

    # Drop the user table
    op.drop_table('user')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fav_user_id_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fav_user_id_fk'], ['user.id'], name='favourite_fav_user_id_fk_fkey'),
    sa.ForeignKeyConstraint(['user_id_fk'], ['user.id'], name='favourite_user_id_fk_fkey'),
    sa.PrimaryKeyConstraint('id', name='favourite_pkey')
    )
    op.create_table('profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id_fk', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('parish', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sex', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('race', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('birth_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('height', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fav_cuisine', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fav_colour', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('fav_school_subject', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('political', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('religious', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('family_oriented', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id_fk'], ['user.id'], name='profile_user_id_fk_fkey'),
    sa.PrimaryKeyConstraint('id', name='profile_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('photo', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('favourites')
    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
